### ISSUE TITLE
Issues in 3.3.5

### ISSUE THREAD

**Issue by Pelonza** [Pelonza/multivariable-calculus-IBL#18]
Figure is included twice. 1 as expandable, also in-text. It only needs to be included in-text.
something strange is going on with in-line matrices after figure 3.3.5
@davidfarmer

**Comment by davidfarmer** [comment]
I don't have the images working in my version, so 
can you post the HTML and send me a link?

For the in-line matrices, are you seeing the word "ensuremath"?
That looks like something that needs to be changes in the LaTeX
before the next conversion (or fixed by hand at the end, if it doesn't
happen too many times).

Anything with "ensuremath" cannot be accurately converted to MBX or HTML,
so it is best to avoid it in the LaTeX.

**Comment by Pelonza** [comment]
Here's the specific HTML that I'm talking about...
http://sl2x.aimath.org/latexsource/schmitt/multivariable-calculus-IBL/html2/review_matrices.html

The image is included as a expandable box (the link) ... but then also under where it appears a second time...

Looking at the latex code... I think it's having a hard time using/rendering a tikzpicture actually. (although this doesn't address the double-occurance of the figure, which is only a bit farther in the text).

-----The ensure math issue seems to be coming from this latex code:
\begin{bmatrix}\cl{1\\0\\0}&\cl{0\\2\\0}&\cl{0\\0\\3}

Specifically, the "\cl{ ... } " command. Because I have "inline" matrices elsewhere using the same matrix command (bmatrix) without any ensure math issues. I believe that code just is meant to center-left the numbers, so can certainly be removed...but might be a future bug to note for fixing MathbookXML process... (or the script?)

**Comment by Pelonza** [comment]
Actually... I'm just going to remove the "\cl{..}" right now... and leave this issue open for the tikzpicture and for your reference...

**Comment by davidfarmer** [comment]
I don't see an image on that page, but I do see
<<SVG image is unavailable, or your browser cannot render it>>

For the \ensuremath, we just need to delete all of those from
the text, because \ensuremath has no place in good LaTeX,
and never works in PTX.  I will delete those in my next pull request.

**Comment by Pelonza** [comment]
I think the missing "images" are actually supposed to be Tikz-pictures... I've started reading the full MBX author's guide... so maybe I can figure this out on my own.

The "ensuremath" seems to be a latex macro that got defined and can probably be safely removed/ignored anyway...  This is the sort of thing I'd been trying to clean up anyway from Ben's original versions.

**Comment by Pelonza** [comment]
So, I saw in one of the [sample textbooks](http://linear.ups.edu/eagts/index.html) on the Mathbook page, successfully included tikz pictures... so I can fix this myself if the script doesn't correctly convert it (it should be a fairly easy fix, unless that author has done major mods).

**Comment by Pelonza** [comment]
Closing this since it's related to the preprocessing of images ...
