### ISSUE TITLE
Cross-Referencing Scope

### ISSUE THREAD

**Issue by Pelonza** [Pelonza/multivariable-calculus-IBL#20]
@davidfarmer

Is it possible to limit the "scope" for cross-referencing? 

Here's what I mean:
Right now, in the latex code, when I want to refer to a specific problem, I use the "\ref{ label } " syntax. Sometimes, I would like that to insert the problem again, sometimes it is just to get the correct exercise/problem number.

An example of this occurs in section 3.1 
http://sl2x.aimath.org/latexsource/schmitt/multivariable-calculus-IBL/html2/section-9.html
--- Problem 3.1.7
Right afterwards, I use a "\ref" to get the correct problem number (in-case it changes)... but it doesn't need to re-insert the problem, due to "scope" ... specifically, either a reference within a section/sub-section (this is an example)... or a reference within a certain amount of rendered lines...

Because if the problem occurs in a DIFFERENT section... it should-reappear. (I don't have an example handy)

**Comment by davidfarmer** [comment]
This may already be a feature request in PTX.

It is a little tricky to figure out how far after the first appearance
the code should wait before inserting the knowl.  I suspect this feature
will not have high priority, because the reader can just not click on it.

In any case, this should be closed and then taken up as in issue with
the PTX code.
