### ISSUE TITLE
next round of markup fixes

### ISSUE THREAD

**Issue by davidfarmer** [Pelonza/multivariable-calculus-IBL#33]
Starting a new issue to keep track of the markup.

My hope is that the main things needed now is to rearrange tags and make sure
things are nested properly.

**Comment by Pelonza** [comment]
Alright, I think I'm back into editing more of the text... 

If I run the validation code now on the text, everything up through chapter 7 passes validation. (minus some todo's in chapter 7). There are still plenty of nesting-tag errors in the remaining sections.

I'm not entirely sure how much of that can easily be fixed via script, or just easier to keep fixing by hand. If you want to take a crack at any of them, please let me know! Otherwise I'm going to keep plugging away at fixing each error manually.

**Comment by davidfarmer** [comment]
If you notice that you are doing the same things a few times,
then let me know and I can see if it can be scripted.

**Comment by Pelonza** [comment]
Here's a list of things I found that are probably scriptable, though I've only got a few chapters left to fix!

the 'blockquote' tags seem to have been converted incorrectly, they are all missing '\<p>' tags.

Any tasks that have "subtasks", several seem to be missing the required "\<introduction>" tag around the "\<p>" tags of things before the first sub-task.

**Comment by davidfarmer** [comment]
I am not likely to get to this in time to be of much help, so I will close this issue
and you will have to do the last bit by hand.
